blog/urls.py
from django.urls import path
from blog import views
from .views import UpdatePostView

app_name = 'blog'

urlpatterns = [
#     blogs
    path("blogs", views.blogs, name="blogs"),
    path("blog/<str:slug>/", views.blogs_comments, name="blogs_comments"),
    path("add_blogs/", views.add_blogs, name="add_blogs"),
    path("edit_blog_post/<str:slug>/", UpdatePostView.as_view(), name="edit_blog_post"),
    path("delete_blog_post/<str:slug>/", views.Delete_Blog_Post, name="delete_blog_post"),
    path("search/", views.search, name="search"),

    path('dummy_blog', views.dummy_blog, name='dummy_blog'),

    
#     profile
    path("profile/", views.Profile, name="profile"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("user_profile/<int:myid>/", views.user_profile, name="user_profile"),
    
#    user authentication
    path("register/", views.Register, name="register"),
    path("login/", views.Login, name="login"),
    path("logout/", views.Logout, name="logout"),
]

empc_08/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from empc_08 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website'),),
    path('', include('blog.urls', namespace='blog'),),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

website/urls.py
from django.urls import path

from website import views

app_name = 'website'


urlpatterns = [
    path('', views.homepage, name='homepage'),
    # path('courses', views.display_courses, name="courses"),
    path('online-courses', views.online_courses, name="online-courses"),
    path('offline-courses', views.offline_courses, name="offline-courses"),
    # path('contact-us', views.contact_us, name='contact-us'),
    path('contact-us', views.ContactUs.as_view(), name='contact-us'),
    path('join-us', views.JoinUs.as_view(), name='join-us'),
    path('about-us', views.about_us, name='about-us'),
    path('course-detail', views.course_detail, name='course-detail'),
    path('thanks', views.ThankYou.as_view(), name='thanks'),
    path('starting-course', views.starting_course_view, name="starting-course"),
    path('know-course', views.know_course_detail_view, name="know-course"),
    path('achieve-course', views.achieve_course_detail_view, name="achieve-course"),
]

website/models.py
from django.db import models

# Create your models here.

STATE_CHOICES = (
  ('Andaman & Nicobar Islands','Andaman & Nicobar Islands'),
  ('Andhra Pradesh','Andhra Pradesh'),
  ('Arunachal Pradesh','Arunachal Pradesh'),
  ('Assam','Assam'),
  ('Bihar','Bihar'),
  ('Chandigarh','Chandigarh'),
  ('Chhattisgarh','Chhattisgarh'),
  ('Dadra & Nagar Haveli','Dadra & Nagar Haveli'),
  ('Daman and Diu','Daman and Diu'),
  ('Delhi','Delhi'),
  ('Goa','Goa'),
  ('Gujarat','Gujarat'),
  ('Haryana','Haryana'),
  ('Himachal Pradesh','Himachal Pradesh'),
  ('Jammu & Kashmir','Jammu & Kashmir'),
  ('Jharkhand','Jharkhand'),
  ('Karnataka','Karnataka'),
  ('Kerala','Kerala'),
  ('Lakshadweep','Lakshadweep'),
  ('Madhya Pradesh','Madhya Pradesh'),
  ('Maharashtra','Maharashtra'),
  ('Manipur','Manipur'),
  ('Meghalaya','Meghalaya'),
  ('Mizoram','Mizoram'),
  ('Nagaland','Nagaland'),
  ('Odisha','Odisha'),
  ('Puducherry','Puducherry'),
  ('Punjab','Punjab'),
  ('Rajasthan','Rajasthan'),
  ('Sikkim','Sikkim'),
  ('Tamil Nadu','Tamil Nadu'),
  ('Telangana','Telangana'),
  ('Tripura','Tripura'),
  ('Uttarakhand','Uttarakhand'),
  ('Uttar Pradesh','Uttar Pradesh'),
  ('West Bengal','West Bengal'),
)



QUERY_TYPE = [
    ('OFFLINE SPOKEN ENLISH CLASSES', 'Offline Spoken English Classes'),
    ('ONLINE SPOKEN ENGLISH CLASSES', 'Online Spoken Enlgish Classes'),
    ('ONLINE GROUP DISCUSSION CLASSES', 'Online Group Discussion Classes'),
    ('IELTS', 'IELTS'),
    ('OTHER', 'Other'),
]


class ContactUs(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.EmailField()
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200, choices=STATE_CHOICES)
    query_type = models.CharField(max_length=100, choices=QUERY_TYPE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


APPLIED_FOR = (
    ('ONLINE SPOKEN ENGLISH TRAINER', 'Online Spoken English Trainer'),
    ('OFFLINE SPOKEN ENGLISH TRAINER', 'Offline Spoken English Trainer'),
    ('IELTS TRAINER', 'IELTS Trainer'),
)



class JoinUs(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.EmailField()
    qualification = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200, choices=STATE_CHOICES)
    applied_for = models.CharField(max_length=100, choices=APPLIED_FOR)
    resume_file = models.FileField(upload_to="trainer_cv")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

website/forms.py
from django import forms
from django.forms import ValidationError

from .models import ContactUs, JoinUs


class HoneypotField(forms.BooleanField):
    default_widget = forms.CheckboxInput(
        {"style": "display:none !important;", "tabindex": "-1", "autocomplete": "off"}
    )

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", HoneypotField.default_widget)
        kwargs["required"] = False
        super().__init__(*args, **kwargs)

    def clean(self, value):
        if cleaned_value := super().clean(value):
            raise ValidationError("")
        else:
            return cleaned_value



class ContactUsForm(forms.ModelForm):
    
    class Meta:
        model = ContactUs
        asdf = HoneypotField()
        fields = ['name', 'phone', 'email', 'city', 'state','query_type', 'message']
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'}),
                   'phone': forms.NumberInput(attrs={'class': 'form-control'}),
                   'email':forms.EmailInput(attrs={'class':'form-control'}),
                   'city':forms.TextInput(attrs={'class':'form-control'}),
                   'state':forms.Select(attrs={'class':'form-control'}),
                   'query_type':forms.Select(attrs={'class':'form-control'}),
                   
                   'message': forms.Textarea(attrs={'class': 'form-control'}),
                   }


class JoinUsForm(forms.ModelForm):
    class Meta:
        model = JoinUs
        fields = ['name', 'phone', 'email', 'qualification', 'city', 'state', 'applied_for', 'resume_file']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'phone':forms.NumberInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'qualification':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'state':forms.Select(attrs={'class':'form-control'}),
            'applied_for':forms.Select(attrs={'class':'form-control'}),
            'resume_file':forms.FileInput(attrs={'class':'form-control'}),
        }

website/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from .forms import ContactUsForm, JoinUsForm


# from .forms import ContactUsForm

def homepage(request):
    return render(request, "website/homepage.html")

def display_courses(request):
    return render(request, "website/courses.html")


def about_us(request):
    return render(request, "website/about_us.html")


# def contact_us(request):
#     return render(request, "website/contact_us.html")

class ContactUs(CreateView):
    form_class = ContactUsForm
    # print(ContactUsForm)
    template_name = "website/contact_us.html"
    success_url = 'thanks' 


class JoinUs(CreateView):
    form_class = JoinUsForm
    # print(ContactUsForm)
    template_name = "website/join_us.html"
    success_url = 'thanks' 




def course_detail(request):
    return render(request, "website/course_detail.html")




class ThankYou(TemplateView):
    template_name = "website/thank_you.html"     


def starting_course_view(request):
    return render(request, "website/starting_detail_view.html")



def know_course_detail_view(request):
    return render(request, "website/know_detail_page.html")


def achieve_course_detail_view(request):
    return render(request, "website/achievment_detail_page.html")


def online_courses(request):
    return render(request, "website/online_course.html")    


def offline_courses(request):
    return render(request, "website/offline_courses.html")

website/templates/website/achievment_detail_page.html
{% extends 'website/base.html' %}
{% load static %}


{% block page_title %}course-detail{% endblock page_title %}

{% block page_content %}
<!-- ========== Start Breadcumb ========== -->
<div class="breadcrumb-nav">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'website:offline-courses' %}">Offline Courses</a></li>
                <li class="breadcrumb-item active" aria-current="page">Achievement</li>
            </ol>
          </nav>
    </div>
</div>
<!-- ========== End Breadcumb ========== -->



<!-- ========== Start course-detail ========== -->
<section class="course-details section-padding">
   <div class="container">
    <div class="row">
        <div class="col-lg-8">
            <!-- ========== Start course-header ========== -->
            <div class="course-header box">
                <h2 class="text-capitalize">Achievement</h2>
                <p>This course provides you the chance to use the grammar that you have learnt.
                    It gives you the platform to speak out your thoughts..</p>
                
                    <h2 class="text-capitalize">Objective</h2>
                <p>To provide the atmosphere where the student can speak with confidence and mistakes are been

                    rectified by the trainer carefully.</p>
                
                

                <div class="course-chapter-list">
                    <h2>Chapter Content</h2>
                    <ul>
                        <li>Hobbies, Interest and personalities</li>
                        <li>Places and work</li>
                        <li>Action at home</li>
                        <li>Likes and Dislikes</li>
                        <li>Directions and Instruction</li>
                        <li>Social Courtesy</li>
                        <li>The Tenses</li>
                        <li>Mock interview</li>
                        <li>Opinion, Request and permission</li>
                        <li>and many ....</li>
                    </ul>
                </div>
            </div>

            <!-- ========== End course-header ========== -->
        </div>
        <div class="col-lg-4">
            <!-- ========== Start course-sidebar ========== -->
            <div class="course-sidebar box">
                 <div class="course-tile">
                    <img src="{% static 'website/images/courses/skae_cover_achievement.png' %}" alt="">
                    
                 </div> 
                 <div class="course-enquire-btn p-2">
                    <a href="{% url 'website:contact-us' %}" class="btn btn-2">Enquire Now</a>  
                 </div>
            </div>
                <!-- ========== End course-sidebar ========== -->
        </div>
    </div>
   </div>
</section>
<!-- ========== End course-detail ========== -->
{% endblock page_content %}

website/templates/website/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <title>SKAE {% block page_title %}{% endblock page_title %}</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{% static 'website/css/owl.carousel.min.css' %}">
  
  <!-- Fontawesome -->
  <link rel="stylesheet" href="{% static 'website/css/font-awesome.css' %}">
  <!-- Bootstrap CSS v5.2.0 -->
  <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
  
  <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'website/css/colors/color-1.css' %}">
  <link rel="stylesheet" class="js-glass-style" href="{% static 'website/css/glass.css' %}">
  <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
  <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Y779EGP311"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y779EGP311');
</script>

  {% block custom_css %}
  
  {% endblock custom_css %}

</head>

<body>

    {% include "website/navbar.html" %}
    <br>
    <div class="main-wrapper">

        {% block page_content %}
    
    {% endblock page_content %}
    </div>
    

  <footer class="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-3">
                    <div class="footer-item">
                        <img src="{% static 'website/images/main_logo.svg' %}" class="footer-logo" alt="footer-logo">
                    <p class="footer-text mt-4">
                        Skae is pioneer in teaching spoken English, has its HO at Gorakhpur started on 13th April 2018.
Skae, formerly known as Shri Krishna Academy for English
                    </p>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="footer-item">
                        <h3>Quick Links</h3>
                        <ul>
                            <li><a href="/">Home</a></li>
                            <li><a href="{% url 'website:about-us' %}">About Us</a></li>
                            <li><a href="/">Courses</a></li>
                            <li><a href="/">Login</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="footer-item">
                        <h3>Get in touch</h3>
                        <ul>
                            <li><a href="https://www.facebook.com/SKAEANS"target="_blank"><i class="fab fa-facebook-f social-icon"></i> Facebook</a></li>
                            <li><a href="https://wa.me/919795949900?text=Hello%20there!!!%0AHow%20may%20I%20help%20you%3F" target="_blank"><i class="fab fa-whatsapp social-icon"></i> Whatsapp</a></li>
                            <li><a href="https://www.instagram.com/skaeindia/" target="_blank"><i class="fab fa-instagram social-icon"></i> Instagram</a></li>
                            <li><a href="https://www.youtube.com/channel/UCNQtY7KkGilCOXYwGhOg7tg" target="_blank"><i class="fab fa-youtube social-icon"></i> Youtube</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="footer-item">
                        <h3>learning</h3>
                        <ul>
                            <li><a href="https://play.google.com/store/apps/details?id=com.edmingle.skae" target="_blank">Get the app</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <p class="m-0 py-4 text-center">Copyright &copy; 2022 SKAE</p>
        </div>
    </div>
  </footer>
  
  {% block custom_js %}
  
  {% endblock custom_js %}
  <!-- Bootstrap JavaScript Libraries -->
  <script src="{% static 'website/js/website.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous">
  </script>

  <script src="{% static 'website/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'website/js/owl.carousel.min.js' %}"></script>
</body>

</html>

website/templates/website/know_detail_page.html
{% extends 'website/base.html' %}
{% load static %}


{% block page_title %}course-detail{% endblock page_title %}






{% block page_content %}
<!-- ========== Start Breadcumb ========== -->
<div class="breadcrumb-nav">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'website:offline-courses' %}">Offline Courses</a></li>
                <li class="breadcrumb-item active" aria-current="page">Know 50+</li>
            </ol>
          </nav>
    </div>
</div>
<!-- ========== End Breadcumb ========== -->



<!-- ========== Start course-detail ========== -->
<section class="course-details section-padding">
   <div class="container">
    <div class="row">
        <div class="col-lg-8">
            <!-- ========== Start course-header ========== -->
            <div class="course-header box">
                <h2 class="text-capitalize">Know 50+</h2>
                <p>This course provides you with the base of Spoken English that is the
                    grammar. It helps you to know about the basics of grammar needed for
                    spoken English.</p>
                
                <h2 class="text-capitalize">Objective</h2>
                <p>To provide the basic of the language with simple examples to the student who has difficulties

                    understanding the language.</p>

                <div class="course-chapter-list">
                    <h2>Content</h2>
                    <ul>
                        <li>Word As Names</li>
                        <li>The Articles</li>
                        <li>Be Form</li>
                        <li>Wh-Questions</li>
                        <li>Position Words</li>
                        <li>Yes/No Questions</li>
                        <li>There/It</li>
                        <li>Subject and Verb Agreement</li>
                        <li>Have/Has/Had</li>
                        <li>Is/Am/Are+ing</li>
                        <li>and more......</li>
                    </ul>
                </div>
            </div>

            <!-- ========== End course-header ========== -->
        </div>
        <div class="col-lg-4">
            <!-- ========== Start course-sidebar ========== -->
            <div class="course-sidebar box">
                 <div class="course-tile">
                    <img src="{% static 'website/images/courses/skae_cover2_for_web.webp' %}" alt="">
                    
                 </div> 
                 <div class="course-enquire-btn p-2">
                    <a href="{% url 'website:contact-us' %}" class="btn btn-2">Enquire Now</a>  
                 </div>
            </div>
                <!-- ========== End course-sidebar ========== -->
        </div>
    </div>
   </div>
</section>
<!-- ========== End course-detail ========== -->
{% endblock page_content %}

website/templates/website/navbar.html
{% load static %}
<div class="main-wrapper">
<header class="header">
    <div class="container">
        <div class="header-main d-flex justify-content-between align-items-center ">
            <div class="header-logo">
                <a href="/"><img src="{% static 'website/images/main_logo.svg' %}" style="width: 140px;
                    height: 75px;" alt="logo"></a>
            </div>
            <button type="button" class="header-hamburger-btn js-header-menu-toggler">
                <span></span>
            </button>
            <div class="header-backdrop js-header-backdrop"></div>
            <nav class="header-menu js-header-menu ">
                <button type="button" class="header-close-btn js-header-menu-toggler">
                    <i class="fas fa-times"></i>
                </button>
                <ul class="menu">
                    <li class="menu-item"><a href="/">Home</a></li>
                    <li class="menu-item"><a href="{% url 'website:about-us' %}">About Us</a></li>
                    <li class="menu-item"><a href="{% url 'blog:blogs' %}">Blog</a></li>
                    <li class="menu-item menu-item-has-children"><a class="js-toggle-sub-menu" href="#">Courses <i class="fas fa-chevron-down"></i></a>
                        <ul class="sub-menu js-sub-menu">
                            {% comment %} <li class="sub-menu-item"><a href="{% url 'website:online-courses' %}">Online Courses</a></li> {% endcomment %}
                            <li class="sub-menu-item"><a href="{% url 'website:offline-courses' %}">Offline Courses</a></li>
                        </ul>
                    </li>
                    
                    <li class="menu-item"><a href="{% url 'website:contact-us' %}">Contact Us</a></li>
                    <li class="menu-item"><a href="{% url 'website:join-us' %}">Join Us</a></li>
                    <li class="menu-item menu-item-has-children"><a class="js-toggle-sub-menu" href="#">Explore <i class="fas fa-chevron-down"></i></a>
                        <ul class="sub-menu js-sub-menu">
                            <li class="sub-menu-item"><a href="https://skae.edmingle.com/">Login</a></li>
                            <li class="sub-menu-item"><a href="#">sign-up</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>
</div>

<!--     


-->



<!--
<nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
              <a class="navbar-brand" href="#"><img src="{% static 'website/images/main_logo.svg' %}" style="width: 140px;
                height: 75px;" alt="logo"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                </ul>
                
              </div>
            </div>
          </nav>

-->

website/templates/website/offline_courses.html
{% extends 'website/base.html' %}
{% load static %}

{% block page_content %}

<!-- ========== Start Breadcumb ========== -->
<div class="breadcrumb-nav">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Offline Courses</li>
            </ol>
          </nav>
    </div>
</div>
<!-- ========== End Breadcumb ========== -->

<!-- ========== Start courses-section ========== -->
<!--Explore Courses start-->
<section class="explore-course section-padding" data-scroll-index="2">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="section-title">
            <h2>Explore our <span>offline courses</span></h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="course-carousel">
          <div class="course-item">
            <img src="{% static 'website/images/courses/img069.webp' %}" alt="">
            <h3 class="course-item-title text-center mt-5">Start 50+</h3>
            <p> This is course is for beginners who lack even basic knowledge of grammar and vacabularies.</p>
  <div class="row justify-content-center mb-2">
    <div class="col-md-3">
        <i class="fas fa-calendar"> 1 Month</i>
    </div>
    <div class="col-md-3">
        <i class="fas fa-clock"> 50 hours</i>
        
    </div>
    <div class="col-md-3">
        <i class="fas fa-book"> 20 Modules</i>
        
    </div>
  </div>
    <a href="{% url 'website:starting-course' %}" class="btn btn-2">View Course</a>
          </div>
          <div class="course-item">
            <img src="{% static 'website/images/courses/skae_cover2_for_web.webp' %}" alt="">
            <h3 class="course-item-title text-center mt-5">Know 50+</h3>
            <p> This course is to learn the concept of Sentence framing, vocabulary and pronunciation with confidence.</p>
            <div class="row justify-content-center mb-2">
                <div class="col-md-3">
                    <i class="fas fa-calendar">   1 Month</i>
                </div>
                <div class="col-md-3">
                    <i class="fas fa-clock"> 100 hours</i>
                    
                </div>
                <div class="col-md-3">
                    <i class="fas fa-book"> 40 Modules</i>
                    
                </div>
              </div>  
            <a href="{% url 'website:know-course' %}" class="btn btn-2">View Course</a>
          </div>
          <div class="course-item">
            <img src="{% static 'website/images/courses/skae_cover_achievement.png' %}" style="" alt="">
            <h3 class="course-item-title text-center mt-5">Achieve 50+</h3>
            
            <p> This course is to provide opportunity to practise and enhance fluency in the presence of a Trainer.</p>
  <div class="row justify-content-center mb-2">
    <div class="col-md-3">
        <i class="fas fa-calendar"> 1 Month</i>
    </div>
    <div class="col-md-3">
        <i class="fas fa-clock"> 50 hours</i>
        
    </div>
    <div class="col-md-3">
        <i class="fas fa-book"> 20 Modules</i>
        
    </div>
  </div>  
  <a href="{% url 'website:achieve-course' %}" class="btn btn-2">View Course</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--Explore Courses end-->
<!-- ========== End courses-section ========== -->


{% endblock page_content %}

website/templates/website/starting_detail_view.html
{% extends 'website/base.html' %}
{% load static %}


{% block page_title %}course-detail{% endblock page_title %}

{% block page_content %}
<!-- ========== Start Breadcumb ========== -->
<div class="breadcrumb-nav">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'website:offline-courses' %}">Offline Courses</a></li>
                <li class="breadcrumb-item active" aria-current="page">Starting</li>
            </ol>
          </nav>
    </div>
</div>
<!-- ========== End Breadcumb ========== -->





<!-- ========== Start course-detail ========== -->
<section class="course-details section-padding">
   <div class="container">
    <div class="row">
        <div class="col-lg-8">
            <!-- ========== Start course-header ========== -->
            <div class="course-header box">
                <h2 class="text-capitalize">Starting</h2>
                <p>This is a beginners course for those aspirants who have just a bit of
                    information about Spoken English and those who are ready to accept the
                    challenge to learn it form the scratch.</p>

                <h2>Objective</h2>
                <p>To provide the basic of the language with simple examples to the student who has difficulties

                    understanding the language.</p>
                
                

                <div class="course-chapter-list">
                    <h2>Chapter Content</h2>
                    <ul>
                        <b><li>Name of numbers, Days &amp; Months.</li>
                        <li>Time and Names of Things Around Us</li>
                        <li>Directions</li>
                        <li>Day to Day Things</li>
                        <li>Pronoun</li>
                        <li>Word to Describe</li>
                        <li>Adverbs</li>
                        <li>Routine Works</li>
                        <li>and more...</li>

                        </b>
                    </ul>
                </div>
            </div>

            <!-- ========== End course-header ========== -->
        </div>
        <div class="col-lg-4">
            <!-- ========== Start course-sidebar ========== -->
            <div class="course-sidebar box">
                 <div class="course-tile">
                    <img src="{% static 'website/images/courses/img069.webp' %}" alt="">
                    
                 </div> 
                 <div class="course-enquire-btn p-2">
                    <a href="{% url 'website:contact-us' %}" class="btn btn-2">Enquire Now</a>  
                 </div>
            </div>
                <!-- ========== End course-sidebar ========== -->
        </div>
    </div>
   </div>
</section>
<!-- ========== End course-detail ========== -->
{% endblock page_content %}